"use client";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { useState } from "react";
import { useGetAccountMeQuery } from "@/account/controller/accountApi";
import { useCreateBoardPostMutation, useCreateBoardCommentMutation, useDeleteBoardCommentMutation, useDeleteBoardPostMutation, useGetAdminBoardCategoriesQuery, useGetBoardCategoriesQuery, useGetBoardCommentsQuery, useGetBoardPostQuery, useGetBoardPostsQuery, useSetBoardNoticeMutation, useUpdateBoardCategoryMutation, useCreateBoardCategoryMutation, useUpdateBoardCommentMutation, useUpdateBoardPostMutation, type BoardCategory, type BoardComment, type PostInput } from "../controller/boardApi";

const button = "inline-flex min-h-10 items-center justify-center rounded-lg border border-zinc-300 bg-white px-4 text-sm font-medium hover:bg-zinc-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-600";
const field = "min-h-11 w-full rounded-lg border border-zinc-300 bg-white px-3 text-sm focus:border-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-100";
const explanation = "기능 요청, 개선 의견, 버그 제보와 자유로운 의견을 남길 수 있는 공간.";
function useRole() { const { data } = useGetAccountMeQuery(); return data?.systemRole; }
function message(error: unknown) { const status = (error as {status?: number})?.status; return status === 403 ? "이 비밀글을 확인할 권한이 없습니다." : status === 404 ? "게시글을 찾을 수 없습니다." : status === 429 ? "요청이 많습니다. 잠시 후 다시 시도해주세요." : "요청을 처리하지 못했습니다. 잠시 후 다시 시도해주세요."; }
function date(value: string) { return new Intl.DateTimeFormat("ko-KR", { dateStyle: "medium" }).format(new Date(value)); }

export function BoardListView() {
  const params = useSearchParams(); const router = useRouter(); const role = useRole();
  const [keyword, setKeyword] = useState(params.get("keyword") ?? "");
  const query = { categoryUid: params.get("categoryUid") ?? undefined, keyword: params.get("keyword") ?? undefined, page: Math.max(0, Number(params.get("page") ?? 0)) };
  const categories = useGetBoardCategoriesQuery(); const posts = useGetBoardPostsQuery(query);
  const setParam = (key: string, value: string) => { const next = new URLSearchParams(params.toString()); if (value) next.set(key, value); else next.delete(key); if (key !== "page") next.delete("page"); router.push(`/board?${next.toString()}`); };
  return <section className="space-y-6">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-bold">게시판</h1><p className="mt-2 text-sm text-zinc-600">{explanation}</p></div><div className="flex gap-2"><Link className={button} href="/board/new">글쓰기</Link>{role === "SUPER_ADMIN" && <Link className={button} href="/admin/board/categories">카테고리 관리</Link>}</div></header>
    <div className="flex flex-col gap-3 rounded-xl border bg-white p-4 sm:flex-row"><select aria-label="카테고리" className={field} value={query.categoryUid ?? ""} onChange={(e) => setParam("categoryUid", e.target.value)}><option value="">전체</option>{categories.data?.filter((c) => c.active).map((c) => <option key={c.categoryUid} value={c.categoryUid}>{c.name}</option>)}</select><form className="flex gap-2 sm:max-w-lg sm:flex-1" onSubmit={(e) => { e.preventDefault(); setParam("keyword", keyword); }}><input className={field} aria-label="검색어" placeholder="제목 또는 내용 검색" value={keyword} onChange={(e) => setKeyword(e.target.value)} /><button className={button}>검색</button>{keyword && <button type="button" className={button} onClick={() => { setKeyword(""); setParam("keyword", ""); }}>지우기</button>}</form></div>
    {posts.isLoading ? <div role="status" className="space-y-3">{[1,2,3,4].map((n) => <div key={n} className="h-16 animate-pulse rounded-xl bg-zinc-200" />)}</div> : posts.isError ? <p role="alert" className="rounded-xl border bg-white p-6">{message(posts.error)}</p> : posts.data?.content.length ? <><div className="overflow-hidden rounded-xl border bg-white"><table className="hidden w-full text-left text-sm md:table"><thead className="bg-zinc-50 text-zinc-600"><tr>{["구분","제목","작성자","댓글","조회","작성일"].map((v) => <th key={v} className="px-4 py-3 font-medium">{v}</th>)}</tr></thead><tbody>{posts.data.content.map((post) => <tr key={post.postUid} className={`border-t ${post.notice ? "bg-amber-50/60" : ""}`}><td className="px-4 py-4">{post.notice ? <span className="rounded bg-amber-100 px-2 py-1 text-xs font-semibold">공지</span> : post.categoryName}</td><td className="px-4 py-4"><Link className="font-medium hover:text-blue-700" href={`/board/${post.postUid}`}>{post.secret ? "🔒 비밀글입니다." : post.title}</Link></td><td className="px-4 py-4">{post.authorDisplayName}</td><td className="px-4 py-4">{post.commentCount}</td><td className="px-4 py-4">{post.viewCount}</td><td className="px-4 py-4">{date(post.createdAt)}</td></tr>)}</tbody></table><div className="divide-y md:hidden">{posts.data.content.map((post) => <Link key={post.postUid} href={`/board/${post.postUid}`} className={`block p-4 ${post.notice ? "bg-amber-50/60" : ""}`}><div className="flex justify-between gap-2 text-xs text-zinc-500"><span>{post.notice ? "공지" : post.categoryName} {post.secret && "· 🔒 비밀글"}</span><span>{date(post.createdAt)}</span></div><p className="mt-2 font-semibold">{post.secret ? "비밀글입니다." : post.title}</p><p className="mt-2 text-xs text-zinc-600">{post.authorDisplayName} · 댓글 {post.commentCount} · 조회 {post.viewCount}</p></Link>)}</div></div><nav aria-label="게시글 페이지" className="flex justify-center gap-2"><button className={button} disabled={query.page <= 0} onClick={() => setParam("page", String(query.page - 1))}>이전</button><span className="self-center text-sm">{query.page + 1} / {Math.max(posts.data.totalPages, 1)}</span><button className={button} disabled={query.page + 1 >= posts.data.totalPages} onClick={() => setParam("page", String(query.page + 1))}>다음</button></nav></> : <p className="rounded-xl border bg-white p-10 text-center text-zinc-600">{query.keyword ? "검색 결과가 없습니다." : "등록된 게시글이 없습니다."}</p>}
  </section>;
}

export function PostFormView({ uid }: { uid?: number }) {
  const router = useRouter(); const role = useRole(); const categories = useGetBoardCategoriesQuery(); const existing = useGetBoardPostQuery(uid!, { skip: !uid });
  const [create, creating] = useCreateBoardPostMutation(); const [update, updating] = useUpdateBoardPostMutation();
  const post = existing.data; const [categoryUid, setCategory] = useState(""); const [title, setTitle] = useState(""); const [content, setContent] = useState(""); const [secret, setSecret] = useState(false); const [notice, setNotice] = useState(false); const [error, setError] = useState("");
  const [initialized, setInitialized] = useState(false); if (post && !initialized) { setCategory(String(post.categoryUid)); setTitle(post.title); setContent(post.content); setSecret(post.secret); setNotice(post.notice); setInitialized(true); }
  const submit = async (e: React.FormEvent) => { e.preventDefault(); setError(""); const body: PostInput = { categoryUid: Number(categoryUid), title: title.trim(), content: content.trim(), secret, ...(!uid && role === "SUPER_ADMIN" ? { notice } : {}) }; try { const result = uid ? await update({ uid, body }).unwrap() : await create(body).unwrap(); router.push(`/board/${result.postUid}`); } catch (err) { setError(message(err)); } };
  if (uid && existing.isError) return <p role="alert" className="rounded-xl border bg-white p-6">{message(existing.error)}</p>;
  return <form onSubmit={submit} className="mx-auto max-w-3xl space-y-5 rounded-xl border bg-white p-5 sm:p-8"><header><h1 className="text-2xl font-bold">{uid ? "게시글 수정" : "게시글 작성"}</h1><p className="mt-2 text-sm text-zinc-600">비밀글은 작성자와 최고 관리자만 확인할 수 있습니다.</p></header><label className="block space-y-2 text-sm font-medium">카테고리<select required className={field} value={categoryUid} onChange={(e) => setCategory(e.target.value)}><option value="">선택하세요</option>{categories.data?.filter((c) => c.active).map((c) => <option key={c.categoryUid} value={c.categoryUid}>{c.name}</option>)}</select></label><label className="block space-y-2 text-sm font-medium">제목<input required maxLength={200} className={field} value={title} onChange={(e) => setTitle(e.target.value)} /></label><label className="block space-y-2 text-sm font-medium">내용<textarea required maxLength={10000} rows={12} className={`${field} py-3`} value={content} onChange={(e) => setContent(e.target.value)} /><span className="block text-right text-xs text-zinc-500">{content.length} / 10000</span></label><label className="flex items-start gap-2 text-sm"><input type="checkbox" checked={secret} onChange={(e) => setSecret(e.target.checked)} /><span><strong>비밀글</strong><span className="block text-zinc-600">비밀글은 작성자와 최고 관리자만 확인할 수 있습니다. 시스템 관리자는 확인할 수 없습니다.</span></span></label>{!uid && role === "SUPER_ADMIN" && <label className="flex gap-2 text-sm"><input type="checkbox" checked={notice} onChange={(e) => setNotice(e.target.checked)} />공지로 등록</label>}{error && <p role="alert" className="text-sm text-red-700">{error}</p>}<div className="flex justify-end gap-2"><Link className={button} href={uid ? `/board/${uid}` : "/board"}>취소</Link><button disabled={creating.isLoading || updating.isLoading} className="min-h-10 rounded-lg bg-blue-700 px-4 text-sm font-semibold text-white disabled:opacity-50">등록</button></div></form>;
}

function Comments({ uid }: { uid: number }) {
  const query = useGetBoardCommentsQuery(uid); const [create] = useCreateBoardCommentMutation(); const [update] = useUpdateBoardCommentMutation(); const [remove] = useDeleteBoardCommentMutation();
  const [content, setContent] = useState(""); const [secret, setSecret] = useState(false); const [reply, setReply] = useState<number | null>(null); const [replyContent, setReplyContent] = useState(""); const [replySecret, setReplySecret] = useState(false); const [error, setError] = useState("");
  const rows = query.data ?? []; const roots = rows.filter((c) => !c.parentCommentUid); const children = (id: number) => rows.filter((c) => c.parentCommentUid === id);
  const send = async (text: string, privateComment: boolean, parentCommentUid?: number) => { try { await create({ uid, content: text, secret: privateComment, parentCommentUid }).unwrap(); setContent(""); setReplyContent(""); setReplySecret(false); setReply(null); } catch (e) { setError(message(e)); } };
  const item = (comment: BoardComment, nested = false) => <article key={comment.commentUid} className={`border-b py-4 ${nested ? "ml-5 border-l-2 border-l-zinc-200 pl-4 sm:ml-8 sm:pl-5" : ""}`}><div className="flex flex-wrap justify-between gap-2 text-sm"><strong>{comment.authorDisplayName}</strong><time className="text-xs text-zinc-500">{date(comment.createdAt)}</time></div><p className={`mt-3 whitespace-pre-wrap break-words ${comment.deleted ? "italic text-zinc-500" : ""}`}>{comment.deleted ? "삭제된 댓글입니다." : comment.content}</p><div className="mt-3 flex gap-3 text-xs">{!nested && <button onClick={() => setReply(reply === comment.commentUid ? null : comment.commentUid)} className="text-blue-700">답글</button>}{comment.canEdit && !comment.deleted && <button onClick={async () => { const value = window.prompt("댓글 내용을 수정하세요", comment.content); if (value) await update({ uid, commentUid: comment.commentUid, content: value, secret: comment.secret }); }}>수정</button>}{comment.canDelete && !comment.deleted && <button onClick={async () => { if (window.confirm("댓글을 삭제하시겠습니까?")) await remove({ uid, commentUid: comment.commentUid }); }}>삭제</button>}</div>{reply === comment.commentUid && <div className="mt-3 space-y-2"><textarea aria-label="답글 내용" className={`${field} py-2`} rows={3} value={replyContent} onChange={(e) => setReplyContent(e.target.value)} /><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={replySecret} onChange={(e) => setReplySecret(e.target.checked)} />비밀 댓글</label><div className="flex justify-end gap-2"><button className={button} onClick={() => setReply(null)}>취소</button><button className={button} onClick={() => void send(replyContent, replySecret, comment.commentUid)}>답글 등록</button></div></div>}{children(comment.commentUid).map((child) => item(child, true))}</article>;
  return <section className="mt-8 rounded-xl border bg-white p-5 sm:p-7"><h2 className="text-xl font-semibold">댓글 {roots.length}</h2><div className="mt-4 space-y-3"><textarea aria-label="댓글 작성" className={`${field} py-3`} rows={4} value={content} onChange={(e) => setContent(e.target.value)} /><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={secret} onChange={(e) => setSecret(e.target.checked)} />비밀 댓글</label><div className="flex justify-end"><button className={button} onClick={() => void send(content, secret)}>등록</button></div></div>{error && <p role="alert" className="mt-3 text-sm text-red-700">{error}</p>}{query.isLoading ? <p role="status" className="mt-5">댓글을 불러오는 중...</p> : roots.length ? roots.map((c) => item(c)) : <p className="mt-6 text-center text-sm text-zinc-500">첫 댓글을 남겨보세요.</p>}</section>;
}

export function PostDetailView({ uid }: { uid: number }) {
  const role = useRole(); const router = useRouter(); const query = useGetBoardPostQuery(uid); const [remove] = useDeleteBoardPostMutation(); const [notice] = useSetBoardNoticeMutation(); const post = query.data;
  if (query.isLoading) return <div role="status" className="h-64 animate-pulse rounded-xl bg-white" />;
  if (query.isError) return <p role="alert" className="rounded-xl border bg-white p-8">{(query.error as {status?:number}).status === 403 ? "이 비밀글을 확인할 권한이 없습니다." : (query.error as {status?:number}).status === 404 ? "게시글을 찾을 수 없습니다." : message(query.error)}</p>;
  if (!post) return null;
  const admin = role === "SUPER_ADMIN";
  const del = async () => { const prompt = admin && !post.canDelete ? "운영 목적으로 이 게시글을 삭제하시겠습니까?" : "이 게시글을 삭제하시겠습니까?"; if (window.confirm(prompt)) { await remove(uid); router.push("/board"); } };
  return <><article className="rounded-xl border bg-white p-5 sm:p-8"><div className="flex flex-wrap items-center gap-2 text-sm text-zinc-600"><span>{post.categoryName}</span>{post.notice && <span className="rounded bg-amber-100 px-2 py-1 text-xs font-semibold">공지</span>}{post.secret && <span>🔒 비밀</span>}</div><h1 className="mt-4 break-words text-2xl font-bold sm:text-3xl">{post.title}</h1><div className="mt-4 flex flex-wrap gap-x-4 gap-y-1 border-b pb-4 text-sm text-zinc-500"><span>{post.authorDisplayName}</span><time>{date(post.createdAt)}</time>{post.updatedAt && <span>수정 {date(post.updatedAt)}</span>}<span>조회 {post.viewCount}</span></div><p className="min-h-40 whitespace-pre-wrap break-words py-8 leading-7">{post.content}</p><div className="flex flex-wrap justify-end gap-2">{post.canEdit && <Link className={button} href={`/board/${uid}/edit`}>수정</Link>}{(post.canDelete || admin) && <button className={button} onClick={() => void del()}>{admin && !post.canDelete ? "운영 삭제" : "삭제"}</button>}{admin && <button className={button} onClick={() => void notice({ uid, notice: !post.notice })}>{post.notice ? "공지 해제" : "공지 등록"}</button>}<Link className={button} href="/board">목록</Link></div></article><Comments uid={uid} /></>;
}

export function BoardCategoryAdminView() {
  const role = useRole(); const query = useGetAdminBoardCategoriesQuery(); const [create] = useCreateBoardCategoryMutation(); const [update] = useUpdateBoardCategoryMutation(); const [editing, setEditing] = useState<BoardCategory | null>(null);
  const save = async (e: React.FormEvent<HTMLFormElement>) => { e.preventDefault(); const form = new FormData(e.currentTarget); const body = { name: String(form.get("name")), description: String(form.get("description")), active: form.get("active") === "on", displayOrder: Number(form.get("displayOrder")) }; if (editing) await update({ uid: editing.categoryUid, body }); else await create(body); setEditing(null); e.currentTarget.reset(); };
  if (role !== "SUPER_ADMIN") return <p role="alert" className="rounded-xl border bg-white p-8">이 페이지에 접근할 권한이 없습니다.</p>;
  return <section className="space-y-6"><header><h1 className="text-2xl font-bold">게시판 카테고리 관리</h1><p className="mt-2 text-sm text-zinc-600">카테고리 추가, 수정, 활성 상태와 정렬 순서를 관리합니다.</p></header><form key={editing?.categoryUid ?? "new"} onSubmit={save} className="grid gap-3 rounded-xl border bg-white p-4 sm:grid-cols-2"><input name="name" required defaultValue={editing?.name} placeholder="이름" className={field} /><input name="description" defaultValue={editing?.description} placeholder="설명" className={field} /><input name="displayOrder" type="number" defaultValue={editing?.displayOrder ?? 0} aria-label="정렬 순서" className={field} /><label className="flex items-center gap-2"><input name="active" type="checkbox" defaultChecked={editing?.active ?? true} />활성</label><button className="min-h-10 rounded-lg bg-blue-700 px-4 text-sm font-semibold text-white">{editing ? "수정 저장" : "카테고리 추가"}</button></form><div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full text-left text-sm"><thead className="bg-zinc-50"><tr>{["이름","설명","활성","정렬 순서","수정"].map((x) => <th key={x} className="p-3">{x}</th>)}</tr></thead><tbody>{query.data?.map((c) => <tr key={c.categoryUid} className="border-t"><td className="p-3">{c.name}</td><td className="p-3">{c.description}</td><td className="p-3">{c.active ? "활성" : "비활성"}</td><td className="p-3">{c.displayOrder}</td><td className="p-3"><button className={button} onClick={() => setEditing(c)}>수정</button></td></tr>)}</tbody></table></div>{query.isError && <p role="alert">{message(query.error)}</p>}</section>;
}
