package com.moneybook.backend.admin.enums;

public enum AdminAuditActionType {
    USER_DETAIL_VIEWED, USER_STATUS_CHANGED, USER_SYSTEM_ROLE_CHANGED,
    MONEY_BOOK_DETAIL_VIEWED, ADMIN_ACTIVITY_SEARCHED, USER_SESSIONS_REVOKED,
    BOARD_CATEGORY_CREATED, BOARD_CATEGORY_UPDATED, BOARD_NOTICE_CHANGED,
    BOARD_POST_MODERATED, BOARD_COMMENT_MODERATED
}
