"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import { getActivityTypeLabel, getTargetTypeLabel, activityTypes, targetTypes, formatActivityTime } from "@/activity/activityLabels";
import { useAdminActivities, useAdminAuditLogs, useAdminMoneyBook, useAdminMoneyBooks, useAdminOverview, useAdminUser, useAdminUsers, useAdminUserMutations } from "../hooks/useAdminQueries";
import { useAdminSession } from "../hooks/useAdminSession";
import { useAdminUrlQuery } from "../hooks/useAdminUrlQuery";
import type { AdminPageResponse } from "../dto/AdminDtos";

const roleLabel = (role: string) => ({ USER: "일반 사용자", SYSTEM_ADMIN: "시스템 관리자", SUPER_ADMIN: "최고 관리자" }[role] ?? role);
const statusLabel = (status: string) => ({ ACTIVE: "정상", BLOCKED: "차단", INACTIVE: "비활성", WITHDRAWN: "탈퇴" }[status] ?? status);
const actionLabel = (action: string) => ({ USER_DETAIL_VIEWED: "사용자 상세 조회", USER_STATUS_CHANGED: "사용자 상태 변경", USER_SYSTEM_ROLE_CHANGED: "시스템 역할 변경", MONEY_BOOK_DETAIL_VIEWED: "가계부 상세 조회", ADMIN_ACTIVITY_SEARCHED: "전체 활동 검색" }[action] ?? action);
const dateTime = (value: string | null | undefined) => value ? new Intl.DateTimeFormat("ko-KR", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Seoul" }).format(new Date(/(?:Z|[+-]\d\d:?\d\d)$/i.test(value) ? value : `${value}+09:00`)) : "-";
const Card = ({ children, className = "" }: { children: React.ReactNode; className?: string }) => <section className={`rounded-xl border border-zinc-200 bg-white p-5 shadow-sm ${className}`}>{children}</section>;
const Heading = ({ title, description }: { title: string; description?: string }) => <div className="mb-6"><h1 className="text-2xl font-bold">{title}</h1>{description && <p className="mt-1 text-sm text-zinc-600">{description}</p>}</div>;
const ErrorBox = ({ message, retry }: { message: string; retry: () => void }) => <div role="alert" className="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-800">{message}<button onClick={retry} className="ml-3 font-semibold underline">다시 시도</button></div>;
function Pager<T>({ data, page, setPage, update }: { data: AdminPageResponse<T>; page: number; setPage: (page: number) => void; update: (key: string, value: string) => void }) { return <div className="mt-5 flex flex-wrap items-center justify-between gap-3 text-sm"><label className="flex items-center gap-2">페이지 크기<select aria-label="페이지 크기" value={data.size} onChange={(e) => update("size", e.target.value)} className="rounded border border-zinc-300 bg-white px-2 py-2">{[20, 50, 100].map((size) => <option key={size}>{size}</option>)}</select></label><div className="flex items-center gap-3"><button aria-label="이전 페이지" disabled={data.first} onClick={() => setPage(Math.max(0, page - 1))} className="min-h-10 rounded border px-3 disabled:opacity-40">이전</button><span aria-live="polite">{data.totalPages === 0 ? 0 : page + 1} / {data.totalPages}</span><button aria-label="다음 페이지" disabled={data.last} onClick={() => setPage(page + 1)} className="min-h-10 rounded border px-3 disabled:opacity-40">다음</button></div></div>; }
function FilterBar({ children, onReset }: { children: React.ReactNode; onReset: () => void }) { return <Card className="mb-5"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{children}</div><button onClick={onReset} className="mt-4 min-h-10 rounded border border-zinc-300 px-4 text-sm font-medium">초기화</button></Card>; }
const fieldClass = "min-h-11 w-full rounded-lg border border-zinc-300 bg-white px-3 text-sm";
function Label({ title, children }: { title: string; children: React.ReactNode }) { return <label className="block text-sm font-medium text-zinc-700">{title}<span className="mt-1.5 block">{children}</span></label>; }

export function AdminOverviewView() {
  const { data, loading, error, retry } = useAdminOverview();
  return <><Heading title="관리자 대시보드" description="서비스 운영 현황을 확인합니다." />{loading && <p role="status">운영 현황을 불러오는 중...</p>}{error && <ErrorBox message={error} retry={retry} />}{data && <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["전체 사용자", data.totalUsers], ["정상 사용자", data.activeUsers], ["정지 사용자", data.suspendedUsers], ["시스템 관리자", data.systemAdminCount], ["최고 관리자", data.superAdminCount], ["전체 가계부", data.totalMoneyBooks], ["오늘 활동", data.activitiesToday]].map(([label, value]) => <Card key={String(label)}><p className="text-sm text-zinc-600">{label}</p><p className="mt-2 text-3xl font-bold tabular-nums">{Number(value).toLocaleString("ko-KR")}</p></Card>)}</div>}</>;
}

export function AdminUsersView() {
  const { params, page, size, update, reset, setPage } = useAdminUrlQuery();
  const query = { page, size, keyword: params.get("keyword") || undefined, status: params.get("status") || undefined, systemRole: params.get("systemRole") || undefined };
  const { data, loading, error, retry } = useAdminUsers(query);
  const canOpenAdminDetails = useAdminSession().isSuperAdmin;
  return <><Heading title="사용자 관리" description="계정 상태와 시스템 역할을 관리합니다." /><FilterBar onReset={reset}><Label title="검색어"><input className={fieldClass} value={params.get("keyword") ?? ""} placeholder="이름 또는 로그인 ID" onChange={(e) => update("keyword", e.target.value)} /></Label><Label title="상태"><select className={fieldClass} value={params.get("status") ?? ""} onChange={(e) => update("status", e.target.value)}><option value="">전체</option>{["ACTIVE", "BLOCKED", "INACTIVE", "WITHDRAWN"].map((v) => <option key={v} value={v}>{statusLabel(v)}</option>)}</select></Label><Label title="시스템 역할"><select className={fieldClass} value={params.get("systemRole") ?? ""} onChange={(e) => update("systemRole", e.target.value)}><option value="">전체</option>{["USER", "SYSTEM_ADMIN", "SUPER_ADMIN"].map((v) => <option key={v} value={v}>{roleLabel(v)}</option>)}</select></Label></FilterBar>{loading && <p role="status">사용자 목록을 불러오는 중...</p>}{error && <ErrorBox message={error} retry={retry} />}{data && <Card><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b text-zinc-600"><th className="p-3">UID</th><th className="p-3">사용자</th><th className="p-3">상태</th><th className="p-3">시스템 역할</th><th className="p-3">가입일</th><th className="p-3">상세</th></tr></thead><tbody>{data.content.map((u) => <tr key={u.userUid} className="border-b last:border-0"><td className="p-3">{u.userUid}</td><td className="p-3"><span className="font-medium">{u.nickname}</span><span className="block text-xs text-zinc-500">{u.loginId}</span></td><td className="p-3">{statusLabel(u.status)}</td><td className="p-3">{roleLabel(u.systemRole)}</td><td className="p-3">{dateTime(u.createdAt)}</td><td className="p-3">{(canOpenAdminDetails || u.systemRole === "USER") ? <Link className="font-semibold text-blue-700 underline" href={`/admin/users/${u.userUid}`}>보기</Link> : <span className="text-zinc-400">제한됨</span>}</td></tr>)}</tbody></table></div>{data.content.length === 0 && <p className="py-8 text-center text-zinc-600">조건에 맞는 사용자가 없습니다.</p>}<Pager data={data} page={page} setPage={setPage} update={update} /></Card>}</>;
}

export function AdminUserDetailView() {
  const route = useParams<{ userUid: string }>(); const uid = Number(route.userUid); const session = useAdminSession(); const { data, loading, error, retry } = useAdminUser(uid); const mutation = useAdminUserMutations();
  if (loading) return <p role="status">사용자 정보를 불러오는 중...</p>;
  if (error) return <><Heading title="사용자 상세" /><Card><p role="alert">{error.includes("403") ? "관리자 권한이 없습니다." : error}</p><button onClick={retry} className="mt-3 underline">다시 시도</button></Card></>;
  if (!data) return null;
  const self = session.user?.userUid === data.userUid; const protectedTarget = data.systemRole === "SUPER_ADMIN" || (session.user?.systemRole === "SYSTEM_ADMIN" && data.systemRole !== "USER");
  const canChangeStatus = !self && !protectedTarget && (session.isSuperAdmin || data.systemRole === "USER");
  const canChangeRole = session.isSuperAdmin && !self && data.systemRole !== "SUPER_ADMIN";
  async function changeStatus() { const status = data!.status === "BLOCKED" ? "ACTIVE" : "BLOCKED"; if (!window.confirm(status === "BLOCKED" ? "이 사용자를 차단하시겠습니까?" : "이 사용자의 차단을 해제하시겠습니까?")) return; try { await mutation.changeStatus({ userUid: data!.userUid, status }).unwrap(); } catch { /* query error surfaced by shared mutation state below */ } }
  async function changeRole(role: "USER" | "SYSTEM_ADMIN") { if (!window.confirm(`이 사용자의 역할을 ${roleLabel(role)}(으)로 변경하시겠습니까?`)) return; try { await mutation.changeRole({ userUid: data!.userUid, systemRole: role }).unwrap(); } catch { /* query error surfaced by shared mutation state below */ } }
  return <><Heading title="사용자 상세" description={`사용자 #${data.userUid}의 운영 정보`} /><Card><div className="grid gap-4 sm:grid-cols-2">{[["닉네임", data.nickname], ["로그인 ID", data.loginId], ["상태", statusLabel(data.status)], ["시스템 역할", roleLabel(data.systemRole)], ["가입일", dateTime(data.createdAt)], ["수정일", dateTime(data.updatedAt)], ["소유 가계부", data.ownedMoneyBookCount], ["참여 가계부", data.joinedMoneyBookCount]].map(([label, value]) => <div key={String(label)} className="border-b border-zinc-100 pb-3"><p className="text-xs text-zinc-500">{label}</p><p className="mt-1 font-medium">{value}</p></div>)}</div>{(self || data.systemRole === "SUPER_ADMIN") && <p className="mt-5 rounded-lg bg-zinc-100 p-3 text-sm text-zinc-700">본인 또는 최고 관리자 계정은 상태와 역할을 변경할 수 없습니다.</p>}{mutation.errorMessage && <p role="alert" className="mt-4 text-sm text-red-700">{mutation.errorMessage}</p>}<div className="mt-6 flex flex-wrap gap-3">{canChangeStatus && <button disabled={mutation.isSaving} onClick={changeStatus} className="min-h-11 rounded-lg border px-4 font-medium disabled:opacity-50">{data.status === "BLOCKED" ? "차단 해제" : "사용자 차단"}</button>}{canChangeRole && <select aria-label="시스템 역할 변경" disabled={mutation.isSaving} value={data.systemRole} onChange={(e) => void changeRole(e.target.value as "USER" | "SYSTEM_ADMIN")} className="min-h-11 rounded-lg border bg-white px-3"><option value="USER">일반 사용자</option><option value="SYSTEM_ADMIN">시스템 관리자</option></select>}</div></Card></>;
}

export function AdminMoneyBooksView() {
  const { params, page, size, update, reset, setPage } = useAdminUrlQuery(); const { data, loading, error, retry } = useAdminMoneyBooks({ page, size, keyword: params.get("keyword") || undefined, ownerUserUid: params.get("ownerUserUid") || undefined });
  return <><Heading title="가계부 관리" description="가계부 운영 메타데이터만 조회합니다. 금융 상세 내용은 제공하지 않습니다." /><FilterBar onReset={reset}><Label title="가계부 이름"><input className={fieldClass} value={params.get("keyword") ?? ""} onChange={(e) => update("keyword", e.target.value)} placeholder="이름 검색" /></Label><Label title="소유자 UID"><input className={fieldClass} inputMode="numeric" value={params.get("ownerUserUid") ?? ""} onChange={(e) => update("ownerUserUid", e.target.value.replace(/\D/g, ""))} placeholder="전체" /></Label></FilterBar>{loading && <p role="status">가계부 목록을 불러오는 중...</p>}{error && <ErrorBox message={error} retry={retry} />}{data && <Card><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead><tr className="border-b text-zinc-600"><th className="p-3">가계부</th><th className="p-3">소유자</th><th className="p-3">멤버</th><th className="p-3">생성일</th><th className="p-3">최근 활동</th></tr></thead><tbody>{data.content.map((book) => <tr key={book.moneyBookUid} className="border-b last:border-0"><td className="p-3"><Link href={`/admin/money-books/${book.moneyBookUid}`} className="font-semibold text-blue-700 underline">{book.name}</Link><span className="block text-xs text-zinc-500">#{book.moneyBookUid}</span></td><td className="p-3">{book.ownerNickname}<span className="block text-xs text-zinc-500">UID {book.ownerUserUid}</span></td><td className="p-3">{book.memberCount}</td><td className="p-3">{dateTime(book.createdAt)}</td><td className="p-3">{dateTime(book.lastActivityAt)}</td></tr>)}</tbody></table></div>{!data.content.length && <p className="py-8 text-center">조건에 맞는 가계부가 없습니다.</p>}<Pager data={data} page={page} setPage={setPage} update={update} /></Card>}</>;
}
export function AdminMoneyBookDetailView() { const route = useParams<{ moneyBookUid: string }>(); const { data, loading, error, retry } = useAdminMoneyBook(Number(route.moneyBookUid)); if (loading) return <p role="status">가계부 운영 정보를 불러오는 중...</p>; if (error) return <><Heading title="가계부 상세" /><ErrorBox message={error} retry={retry} /></>; if (!data) return null; return <><Heading title={data.name} description={`가계부 #${data.moneyBookUid} · 운영 메타데이터`} /><Card><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[["소유자", `${data.ownerNickname} (UID ${data.ownerUserUid})`], ["멤버 수", data.memberCount], ["카테고리 수", data.categoryCount], ["계좌 수", data.accountCount], ["거래 수", data.transactionCount], ["이체 수", data.transferCount], ["월 결산 수", data.monthClosingCount], ["생성일", dateTime(data.createdAt)], ["최근 활동", dateTime(data.lastActivityAt)]].map(([label, value]) => <div key={String(label)} className="rounded-lg bg-zinc-50 p-4"><p className="text-sm text-zinc-600">{label}</p><p className="mt-1 font-semibold">{value}</p></div>)}</div><p className="mt-5 text-sm text-zinc-600">거래 내역, 메모, 계좌 잔액 및 개인 소비 정보는 이 화면에서 조회하지 않습니다.</p></Card></>; }

export function AdminActivitiesView() {
  const { params, page, size, update, reset, setPage } = useAdminUrlQuery(); const filters = { page, size, moneyBookUid: params.get("moneyBookUid") || undefined, actorUserUid: params.get("actorUserUid") || undefined, activityType: params.get("activityType") || undefined, targetType: params.get("targetType") || undefined, startDate: params.get("startDate") || undefined, endDate: params.get("endDate") || undefined }; const { data, loading, error, retry } = useAdminActivities(filters);
  const rangeInvalid = Boolean(filters.startDate && filters.endDate && filters.startDate > filters.endDate);
  return <><Heading title="전체 활동내역" description="모든 가계부에서 기록된 활동을 최신순으로 조회합니다." /><FilterBar onReset={reset}><Label title="가계부 UID"><input className={fieldClass} inputMode="numeric" value={params.get("moneyBookUid") ?? ""} onChange={(e) => update("moneyBookUid", e.target.value.replace(/\D/g, ""))} /></Label><Label title="사용자 UID"><input className={fieldClass} inputMode="numeric" value={params.get("actorUserUid") ?? ""} onChange={(e) => update("actorUserUid", e.target.value.replace(/\D/g, ""))} /></Label><Label title="활동 유형"><select className={fieldClass} value={params.get("activityType") ?? ""} onChange={(e) => update("activityType", e.target.value)}><option value="">전체</option>{activityTypes.map((v) => <option key={v} value={v}>{getActivityTypeLabel(v)}</option>)}</select></Label><Label title="대상 유형"><select className={fieldClass} value={params.get("targetType") ?? ""} onChange={(e) => update("targetType", e.target.value)}><option value="">전체</option>{targetTypes.map((v) => <option key={v} value={v}>{getTargetTypeLabel(v)}</option>)}</select></Label><Label title="시작일"><input className={fieldClass} type="date" value={params.get("startDate") ?? ""} onChange={(e) => update("startDate", e.target.value)} /></Label><Label title="종료일"><input className={fieldClass} type="date" value={params.get("endDate") ?? ""} onChange={(e) => update("endDate", e.target.value)} /></Label></FilterBar>{rangeInvalid && <p role="alert" className="mb-4 text-sm text-red-700">시작일은 종료일보다 늦을 수 없습니다.</p>}{loading && <p role="status">활동내역을 불러오는 중...</p>}{error && <ErrorBox message={error} retry={retry} />}{data && !rangeInvalid && <Card><div className="space-y-4">{data.content.map((entry) => { const time = formatActivityTime(entry.occurredAt); return <article key={entry.activityUid} className="border-l-2 border-blue-200 pl-4"><div className="flex flex-wrap items-center gap-2"><strong>{entry.actorNickname}</strong><span className="rounded-full bg-blue-50 px-2 py-1 text-xs">{getActivityTypeLabel(entry.activityType)}</span><span className="rounded-full bg-zinc-100 px-2 py-1 text-xs">{getTargetTypeLabel(entry.targetType)}</span></div><p className="mt-1">{entry.summary}</p><p className="mt-1 text-xs text-zinc-500">{entry.moneyBookName ?? `가계부 #${entry.moneyBookUid}`} · {time.dateKey} {time.time}</p></article>; })}</div>{data.content.length === 0 && <p className="py-8 text-center text-zinc-600">조건에 맞는 활동내역이 없습니다.</p>}<Pager data={data} page={page} setPage={setPage} update={update} /></Card>}</>;
}

export function AdminAuditLogsView() {
  const { params, page, size, update, reset, setPage } = useAdminUrlQuery(); const { data, loading, error, retry } = useAdminAuditLogs({ page, size, actorUserUid: params.get("actorUserUid") || undefined, actionType: params.get("actionType") || undefined, targetType: params.get("targetType") || undefined, startDate: params.get("startDate") || undefined, endDate: params.get("endDate") || undefined }); const invalid = Boolean(params.get("startDate") && params.get("endDate") && params.get("startDate")! > params.get("endDate")!);
  return <><Heading title="관리자 감사로그" description="관리자 운영 작업에 대한 변경 불가 기록입니다." /><FilterBar onReset={reset}><Label title="관리자 UID"><input className={fieldClass} inputMode="numeric" value={params.get("actorUserUid") ?? ""} onChange={(e) => update("actorUserUid", e.target.value.replace(/\D/g, ""))} /></Label><Label title="작업"><select className={fieldClass} value={params.get("actionType") ?? ""} onChange={(e) => update("actionType", e.target.value)}><option value="">전체</option>{["USER_DETAIL_VIEWED", "USER_STATUS_CHANGED", "USER_SYSTEM_ROLE_CHANGED", "MONEY_BOOK_DETAIL_VIEWED", "ADMIN_ACTIVITY_SEARCHED"].map((v) => <option key={v} value={v}>{actionLabel(v)}</option>)}</select></Label><Label title="대상"><select className={fieldClass} value={params.get("targetType") ?? ""} onChange={(e) => update("targetType", e.target.value)}><option value="">전체</option>{["USER", "MONEY_BOOK", "ACTIVITY"].map((v) => <option key={v}>{v}</option>)}</select></Label><Label title="시작일"><input className={fieldClass} type="date" value={params.get("startDate") ?? ""} onChange={(e) => update("startDate", e.target.value)} /></Label><Label title="종료일"><input className={fieldClass} type="date" value={params.get("endDate") ?? ""} onChange={(e) => update("endDate", e.target.value)} /></Label></FilterBar>{invalid && <p role="alert" className="mb-4 text-sm text-red-700">시작일은 종료일보다 늦을 수 없습니다.</p>}{loading && <p role="status">감사로그를 불러오는 중...</p>}{error && <ErrorBox message={error} retry={retry} />}{data && !invalid && <Card><div className="space-y-4">{data.content.map((row) => <article key={row.adminAuditLogUid} className="rounded-lg border border-zinc-200 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><strong>{row.actorNickname}</strong><span className="text-xs text-zinc-500">{dateTime(row.occurredAt)}</span></div><p className="mt-2">{row.summary}</p><p className="mt-1 text-sm text-zinc-600">{roleLabel(row.actorSystemRole)} · {actionLabel(row.actionType)} · {row.targetType}{row.targetUid ? ` #${row.targetUid}` : ""}</p></article>)}</div>{!data.content.length && <p className="py-8 text-center">감사로그가 없습니다.</p>}<Pager data={data} page={page} setPage={setPage} update={update} /></Card>}</>;
}
