package com.moneybook.backend.transaction.repository;

import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.Test;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.datasource.SingleConnectionDataSource;
import org.springframework.jdbc.datasource.init.ScriptUtils;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

class LedgerMigrationTests {

    @Test
    void flywayAppliesLedgerMigrationAfterExistingBookSchema() throws Exception {
        try (Connection connection = DriverManager.getConnection(
                "jdbc:h2:mem:ledger_flyway;MODE=PostgreSQL", "sa", "")) {
            try (Statement statement = connection.createStatement()) {
                statement.execute("CREATE TABLE users (user_uid BIGINT PRIMARY KEY)");
                // This fixture baselines after the users migration, so retain its LOCAL credential table too.
                statement.execute("CREATE TABLE user_auth (user_auth_uid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_uid BIGINT NOT NULL, provider VARCHAR(30) NOT NULL, login_id VARCHAR(100), password_hash VARCHAR(255), provider_user_id VARCHAR(255))");
                statement.execute("INSERT INTO user_auth(user_uid,provider,login_id,password_hash) VALUES (1,'LOCAL','existing','existing-hash')");
            }
            ScriptUtils.executeSqlScript(connection,
                    new ClassPathResource("db/migration/V20261001_2__create_money_books.sql"));
            Flyway.configure()
                    .dataSource(new SingleConnectionDataSource(connection, true))
                    .locations("classpath:db/migration")
                    .baselineOnMigrate(true)
                    .baselineVersion("20261001.2")
                    .load()
                    .migrate();
            try (Statement statement = connection.createStatement();
                 ResultSet result = statement.executeQuery("""
                         SELECT COUNT(*) FROM "flyway_schema_history"
                         WHERE "version" = '20261002.1' AND "success" = TRUE
                         """)) {
                result.next();
                assertEquals(1, result.getInt(1));
            }
            try (Statement statement = connection.createStatement(); ResultSet result = statement.executeQuery(
                    "SELECT security_question_code,security_answer_hash,verified_email,password_change_required FROM user_auth WHERE login_id='existing'")) {
                result.next();assertEquals(null,result.getString(1));assertEquals(null,result.getString(2));
                assertEquals(null,result.getString(3));assertEquals(false,result.getBoolean(4));
            }
            try (Statement statement = connection.createStatement(); ResultSet result = statement.executeQuery(
                    "SELECT COUNT(*) FROM \"flyway_schema_history\" WHERE \"version\"='20261004.3' AND \"success\"=TRUE")) {
                result.next();assertEquals(1,result.getInt(1));
            }
        }
    }

    @Test
    void verifiedEmailMigrationNormalizesValuesAndUniqueIndexAllowsNulls() throws Exception {
        try (Connection connection = DriverManager.getConnection(
                "jdbc:h2:mem:verified_email_migration;MODE=PostgreSQL", "sa", "")) {
            try (Statement statement = connection.createStatement()) {
                statement.execute("CREATE TABLE user_auth (user_auth_uid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, verified_email VARCHAR(254))");
                statement.execute("CREATE UNIQUE INDEX uq_user_auth_verified_email ON user_auth (verified_email)");
                statement.execute("INSERT INTO user_auth (verified_email) VALUES ('  Alice@Example.com  '), ('Bob@Example.com')");
            }
            ScriptUtils.executeSqlScript(connection,
                    new ClassPathResource("db/migration/V20261004_3__normalize_verified_email_uniqueness.sql"));
            try (Statement statement = connection.createStatement(); ResultSet result = statement.executeQuery(
                    "SELECT verified_email FROM user_auth ORDER BY user_auth_uid")) {
                result.next();assertEquals("alice@example.com",result.getString(1));
                result.next();assertEquals("bob@example.com",result.getString(1));
            }
            try (Statement statement = connection.createStatement()) {
                statement.execute("INSERT INTO user_auth (verified_email) VALUES (NULL), (NULL)");
                assertThrows(SQLException.class, () -> statement.execute(
                        "INSERT INTO user_auth (verified_email) VALUES ('alice@example.com')"));
                statement.execute("UPDATE user_auth SET verified_email='new@example.com' WHERE user_auth_uid=1");
                statement.execute("INSERT INTO user_auth (verified_email) VALUES ('alice@example.com')");
                statement.execute("UPDATE user_auth SET verified_email=NULL WHERE user_auth_uid=2");
                statement.execute("INSERT INTO user_auth (verified_email) VALUES ('bob@example.com')");
            }
        }
    }

    @Test
    void verifiedEmailMigrationFailsInsteadOfDeletingExistingNormalizedDuplicates() throws Exception {
        try (Connection connection = DriverManager.getConnection(
                "jdbc:h2:mem:verified_email_collision;MODE=PostgreSQL", "sa", "")) {
            try (Statement statement = connection.createStatement()) {
                statement.execute("CREATE TABLE user_auth (user_auth_uid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, verified_email VARCHAR(254))");
                statement.execute("CREATE UNIQUE INDEX uq_user_auth_verified_email ON user_auth (verified_email)");
                statement.execute("INSERT INTO user_auth (verified_email) VALUES ('Alice@Example.com'), (' alice@example.com ')");
            }
            assertThrows(RuntimeException.class, () -> ScriptUtils.executeSqlScript(connection,
                    new ClassPathResource("db/migration/V20261004_3__normalize_verified_email_uniqueness.sql")));
            try (Statement statement = connection.createStatement(); ResultSet result = statement.executeQuery(
                    "SELECT COUNT(*) FROM user_auth")) {
                result.next();assertEquals(2,result.getInt(1));
            }
        }
    }

    @Test
    void migrationCreatesAuditedTablesAndEnforcesAmountAndBookReferences() throws Exception {
        try (Connection connection = DriverManager.getConnection(
                "jdbc:h2:mem:ledger_migration;MODE=PostgreSQL", "sa", "")) {
            try (Statement statement = connection.createStatement()) {
                statement.execute("""
                        CREATE TABLE users (user_uid BIGINT PRIMARY KEY, nickname VARCHAR(50) NOT NULL,
                                            status VARCHAR(30) NOT NULL, reg_time TIMESTAMP NOT NULL,
                                            mod_time TIMESTAMP NOT NULL)
                        """);
            }
            ScriptUtils.executeSqlScript(connection,
                    new ClassPathResource("db/migration/V20261001_2__create_money_books.sql"));
            ScriptUtils.executeSqlScript(connection,
                    new ClassPathResource("db/migration/V20261002_1__create_ledger_tables.sql"));

            try (Statement statement = connection.createStatement()) {
                try (ResultSet result = statement.executeQuery("""
                        SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
                        WHERE TABLE_NAME IN ('MONEY_BOOK_CATEGORIES', 'MONEY_BOOK_ACCOUNTS',
                                             'MONEY_BOOK_TRANSACTIONS')
                          AND COLUMN_NAME IN ('REG_R_ID', 'REG_TIME', 'MOD_R_ID', 'MOD_TIME')
                        """)) {
                    result.next();
                    assertEquals(12, result.getInt(1));
                }
                statement.execute("""
                        INSERT INTO users (user_uid, nickname, status, reg_time, mod_time)
                        VALUES (1, 'owner', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                        """);
                statement.execute("""
                        INSERT INTO money_books (money_book_uid, name, owner_user_uid, reg_time, mod_time)
                        VALUES (1, 'first', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                               (2, 'second', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                        """);
                statement.execute("""
                        INSERT INTO money_book_categories
                            (category_uid, money_book_uid, name, transaction_type, sort_order, reg_time, mod_time)
                        VALUES (1, 1, 'food', 'EXPENSE', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                        """);
                statement.execute("""
                        INSERT INTO money_book_accounts
                            (account_uid, money_book_uid, name, account_type, sort_order, reg_time, mod_time)
                        VALUES (1, 1, 'cash', 'CASH', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                               (2, 2, 'other', 'BANK', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                        """);
                assertThrows(SQLException.class, () -> statement.execute("""
                        INSERT INTO money_book_transactions
                            (money_book_uid, transaction_type, amount, transaction_date, category_uid,
                             account_uid, reg_time, mod_time)
                        VALUES (1, 'EXPENSE', 0, DATE '2026-10-02', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                        """));
                assertThrows(SQLException.class, () -> statement.execute("""
                        INSERT INTO money_book_transactions
                            (money_book_uid, transaction_type, amount, transaction_date, category_uid,
                             account_uid, reg_time, mod_time)
                        VALUES (1, 'EXPENSE', -1, DATE '2026-10-02', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                        """));
                assertThrows(SQLException.class, () -> statement.execute("""
                        INSERT INTO money_book_transactions
                            (money_book_uid, transaction_type, amount, transaction_date, category_uid,
                             account_uid, reg_time, mod_time)
                        VALUES (1, 'EXPENSE', 100, DATE '2026-10-02', 1, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                        """));
                assertThrows(SQLException.class, () -> statement.execute("""
                        INSERT INTO money_book_transactions
                            (money_book_uid, transaction_type, amount, transaction_date, category_uid,
                             account_uid, reg_time, mod_time)
                        VALUES (1, 'INCOME', 100, DATE '2026-10-02', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                        """));
                assertThrows(SQLException.class, () -> statement.execute("""
                        INSERT INTO money_book_categories
                            (money_book_uid, name, transaction_type, sort_order, reg_time, mod_time)
                        VALUES (1, 'food', 'EXPENSE', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                        """));
                assertThrows(SQLException.class, () -> statement.execute("""
                        INSERT INTO money_book_categories
                            (money_book_uid, name, transaction_type, sort_order, reg_time, mod_time)
                        VALUES (1, 'invalid', 'EXPENSE', -1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                        """));
                assertThrows(SQLException.class, () -> statement.execute("""
                        INSERT INTO money_book_accounts
                            (money_book_uid, name, account_type, sort_order, reg_time, mod_time)
                        VALUES (1, 'cash', 'CASH', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                        """));
                assertThrows(SQLException.class, () -> statement.execute("""
                        INSERT INTO money_book_accounts
                            (money_book_uid, name, account_type, sort_order, reg_time, mod_time)
                        VALUES (1, 'invalid', 'CARD', -1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                        """));
            }
        }
    }
}
