"use client";
import { useGetAdminActivitiesQuery, useGetAdminAuditLogsQuery, useGetAdminMoneyBookQuery, useGetAdminMoneyBooksQuery, useGetAdminOverviewQuery, useGetAdminUserQuery, useGetAdminUsersQuery, useChangeAdminSystemRoleMutation, useChangeAdminUserStatusMutation } from "../controller/adminApi";
import type { AdminActivityQuery, AdminAuditQuery, AdminListQuery } from "../dto/AdminDtos";
import { getApiErrorMessage } from "@/common/api/getApiErrorMessage";

export function useAdminOverview() { const query = useGetAdminOverviewQuery(); return { data: query.currentData, loading: query.isLoading, error: query.isError ? getApiErrorMessage(query.error, "운영 현황을 불러오지 못했습니다.") : null, retry: query.refetch }; }
export function useAdminUsers(query: AdminListQuery) { const result = useGetAdminUsersQuery(query); return { data: result.currentData, loading: result.isLoading, fetching: result.isFetching, error: result.isError ? getApiErrorMessage(result.error, "사용자 목록을 불러오지 못했습니다.") : null, retry: result.refetch }; }
export function useAdminUser(uid: number) { const query = useGetAdminUserQuery(uid, { skip: !Number.isSafeInteger(uid) || uid <= 0 }); return { data: query.currentData, loading: query.isLoading, error: query.isError ? getApiErrorMessage(query.error, "사용자 정보를 불러오지 못했습니다.") : null, retry: query.refetch }; }
export function useAdminMoneyBooks(query: AdminListQuery) { const result = useGetAdminMoneyBooksQuery(query); return { data: result.currentData, loading: result.isLoading, fetching: result.isFetching, error: result.isError ? getApiErrorMessage(result.error, "가계부 목록을 불러오지 못했습니다.") : null, retry: result.refetch }; }
export function useAdminMoneyBook(uid: number) { const query = useGetAdminMoneyBookQuery(uid, { skip: !Number.isSafeInteger(uid) || uid <= 0 }); return { data: query.currentData, loading: query.isLoading, error: query.isError ? getApiErrorMessage(query.error, "가계부 정보를 불러오지 못했습니다.") : null, retry: query.refetch }; }
export function useAdminActivities(query: AdminActivityQuery) { const result = useGetAdminActivitiesQuery(query); return { data: result.currentData, loading: result.isLoading, fetching: result.isFetching, error: result.isError ? getApiErrorMessage(result.error, "전체 활동내역을 불러오지 못했습니다.") : null, retry: result.refetch }; }
export function useAdminAuditLogs(query: AdminAuditQuery) { const result = useGetAdminAuditLogsQuery(query); return { data: result.currentData, loading: result.isLoading, fetching: result.isFetching, error: result.isError ? getApiErrorMessage(result.error, "감사로그를 불러오지 못했습니다.") : null, retry: result.refetch }; }
export function useAdminUserMutations() { const [status, statusState] = useChangeAdminUserStatusMutation(); const [role, roleState] = useChangeAdminSystemRoleMutation(); const error = statusState.error || roleState.error; return { changeStatus: status, changeRole: role, isSaving: statusState.isLoading || roleState.isLoading, errorMessage: error ? getApiErrorMessage(error, "요청을 처리하지 못했습니다. 권한을 확인하고 다시 시도해 주세요.") : null }; }
