"use client";

import Link from "../../common/components/MoneyLink";
import MonthSelector from "@/transaction/components/MonthSelector";
import { formatLocalizedAmount } from "@/common/format/money";
import { formatLocalDate } from "@/common/format/dateTime";
import { formatPercentPoints, formatFractionPercent } from "@/common/format/percent";
import { useTranslation } from "@/i18n/useTranslation";
import { useMonthlyDashboard } from "@/dashboard/hooks/useMonthlyDashboard";

function Comparison({ value, label, unavailable }: { value: number | null; label: string; unavailable: string }) {
  return <p className="mt-1 text-xs text-zinc-600">{label}: {value === null ? unavailable : `${value > 0 ? "+" : ""}${formatPercentPoints(value)}`}</p>;
}

function amount(value: number, locale: "ko" | "en" | "ja" | "zh") { return formatLocalizedAmount(value, locale); }
function monthName(year: number, month: number, locale: "ko" | "en" | "ja" | "zh", includeYear: boolean) {
  return new Intl.DateTimeFormat(({ ko: "ko-KR", en: "en-US", ja: "ja-JP", zh: "zh-CN" })[locale], { month: "long", ...(includeYear ? { year: "numeric" } : {}), timeZone: "UTC" }).format(new Date(Date.UTC(year, month - 1, 1)));
}

export default function MoneyBookDetail({ moneyBookUid }: { moneyBookUid: number }) {
  const data = useMonthlyDashboard(moneyBookUid);
  const { year, month, dashboard, permission } = data;
  const { locale, t } = useTranslation();
  const root = `/books/${moneyBookUid}`;
  if (permission.isLoading) return <p role="status" className="rounded-xl border bg-white p-5">{t("dashboard.loading")}</p>;
  if (permission.isError) return <p role="alert" className="rounded-xl border bg-white p-5 text-red-700">{permission.errorMessage}</p>;
  if (!permission.moneyBook) return <p role="alert" className="rounded-xl border bg-white p-5">{t("books.accessMissing")}</p>;
  if (!permission.canRead) return <p role="alert" className="rounded-xl border bg-white p-5">{t("books.accessDenied")}</p>;
  const trendMax = Math.max(1, ...(dashboard?.monthlyTrend.flatMap((item) => [item.income, item.expense]) ?? []));
  return <main className="min-w-0 space-y-6">
    <header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm text-zinc-600">{permission.moneyBook.name}</p><h1 className="mt-1 text-2xl font-semibold">{t("dashboard.title")}</h1><p className="mt-1 text-sm text-zinc-600">{t("dashboard.subtitle")}</p></div><div className="flex flex-wrap items-center gap-2"><MonthSelector year={year} month={month} allowPrevious={year > 2} allowNext={year < 9998} onPrevious={() => data.moveMonth(-1)} onNext={() => data.moveMonth(1)} /><button type="button" onClick={data.goToToday} className="min-h-11 rounded-lg border px-3 text-sm">{t("dashboard.today")}</button></div></header>
    {data.isLoading && !dashboard ? <div role="status" className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4" aria-label={t("dashboard.loading")}>{[1,2,3,4].map((item) => <div key={item} className="h-24 animate-pulse rounded-xl bg-zinc-100" />)}</div> : data.isError && !dashboard ? <div role="alert" className="rounded-xl border bg-white p-5 text-red-700"><p>{data.errorMessage}</p><button type="button" onClick={() => void data.refetch()} className="mt-3 min-h-10 rounded-lg border px-3">{t("dashboard.retry")}</button></div> : dashboard && <>
      {data.isFetching && <p role="status" className="text-xs text-zinc-500">{t("dashboard.refreshing")}</p>}
      <section aria-label={t("dashboard.summary")} className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
        <article className="rounded-xl border bg-white p-4"><h2 className="text-sm text-zinc-600">{t("dashboard.income")}</h2><p className="mt-2 text-xl font-semibold text-blue-700">{amount(dashboard.summary.totalIncome, locale)}</p><Comparison value={dashboard.comparison.incomeChangeRate} label={t("dashboard.comparison")} unavailable={t("dashboard.comparisonUnavailable")} /></article>
        <article className="rounded-xl border bg-white p-4"><h2 className="text-sm text-zinc-600">{t("dashboard.expense")}</h2><p className="mt-2 text-xl font-semibold text-rose-700">{amount(dashboard.summary.totalExpense, locale)}</p><Comparison value={dashboard.comparison.expenseChangeRate} label={t("dashboard.comparison")} unavailable={t("dashboard.comparisonUnavailable")} /></article>
        <article className="rounded-xl border bg-white p-4"><h2 className="text-sm text-zinc-600">{t("dashboard.balance")}</h2><p className="mt-2 text-xl font-semibold">{amount(dashboard.summary.balance, locale)}</p><p className="mt-1 text-xs text-zinc-600">{t("dashboard.balanceHint")}</p></article>
        <article className="rounded-xl border bg-white p-4"><h2 className="text-sm text-zinc-600">{t("dashboard.transactionCount")}</h2><p className="mt-2 text-xl font-semibold">{new Intl.NumberFormat(({ko:"ko-KR",en:"en-US",ja:"ja-JP",zh:"zh-CN"})[locale]).format(dashboard.summary.transactionCount)}</p><p className="mt-1 text-xs text-zinc-600">{t("dashboard.income")} {dashboard.summary.incomeCount} ? {t("dashboard.expense")} {dashboard.summary.expenseCount}</p></article>
      </section>
      {dashboard.summary.transactionCount === 0 && <p className="rounded-lg bg-blue-50 px-4 py-3 text-sm text-blue-900">{t("dashboard.emptyMonth")}</p>}
      <section className="grid gap-5 xl:grid-cols-2">
        <article className="min-w-0 rounded-xl border bg-white p-4 sm:p-5"><h2 className="font-semibold">{t("dashboard.trend")}</h2><p className="mt-1 text-xs text-zinc-600">{t("dashboard.trendHint")}</p><div role="img" aria-label={t("dashboard.trend")} className="mt-5 grid grid-cols-6 gap-2">{dashboard.monthlyTrend.map((item) => <div key={`${item.year}-${item.month}`} className="flex min-w-0 flex-col items-center gap-2"><div className="flex h-36 w-full items-end justify-center gap-1" title={`${monthName(item.year,item.month,locale,true)}: ${t("dashboard.income")} ${amount(item.income,locale)}, ${t("dashboard.expense")} ${amount(item.expense,locale)}`}><span className="w-3 rounded-t bg-blue-600 sm:w-5" style={{height:`${item.income>0?Math.max(3,item.income/trendMax*100):0}%`}}/><span className="w-3 rounded-t bg-rose-500 sm:w-5" style={{height:`${item.expense>0?Math.max(3,item.expense/trendMax*100):0}%`}}/></div><span className="text-xs">{monthName(item.year,item.month,locale,false)}</span></div>)}</div><div className="mt-3 flex gap-4 text-xs"><span><i className="mr-1 inline-block size-2 rounded-full bg-blue-600" />{t("dashboard.income")}</span><span><i className="mr-1 inline-block size-2 rounded-full bg-rose-500" />{t("dashboard.expense")}</span></div><ul className="mt-4 space-y-1 text-sm">{dashboard.monthlyTrend.map((item)=><li key={`${item.year}-${item.month}`} className="flex flex-wrap justify-between gap-1"><span>{monthName(item.year,item.month,locale,true)}</span><span className="text-right">{t("dashboard.income")} {amount(item.income,locale)} ? {t("dashboard.expense")} {amount(item.expense,locale)}</span></li>)}</ul></article>
        <article className="rounded-xl border bg-white p-4 sm:p-5"><h2 className="font-semibold">{t("dashboard.categoryExpenses")}</h2>{dashboard.categoryExpenses.length===0?<p className="mt-3 text-sm text-zinc-600">{t("dashboard.noExpenses")}</p>:<ul className="mt-3 space-y-3">{dashboard.categoryExpenses.map((item)=><li key={item.categoryUid}><div className="flex flex-wrap justify-between gap-1 text-sm"><span className="min-w-0 break-words font-medium">{item.categoryName}</span><span className="shrink-0">{amount(item.amount,locale)}</span></div><div className="mt-1 flex items-center gap-2"><div className="h-2 flex-1 overflow-hidden rounded-full bg-zinc-100"><div className="h-full rounded-full bg-indigo-500" style={{width:`${Math.min(100,Math.max(0,item.ratio*100))}%`}}/></div><span className="w-14 text-right text-xs text-zinc-600">{formatFractionPercent(item.ratio)}</span></div><p className="mt-1 text-xs text-zinc-500">{item.transactionCount} {t("dashboard.transactions")}</p></li>)}</ul>}</article>
      </section>
      <section className="rounded-xl border bg-white p-4 sm:p-5"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="font-semibold">{t("dashboard.budget")}</h2><Link href={`${root}/budgets?year=${year}&month=${month}`} className="text-sm text-blue-700 hover:underline">{t("dashboard.budgetManage")}</Link></div>{!dashboard.budget?<p className="mt-3 text-sm text-zinc-600">{t("dashboard.budgetUnset")}</p>:<><div className="mt-3 grid gap-3 text-sm sm:grid-cols-3"><p>{t("dashboard.budgetTotal")}<strong className="mt-1 block">{dashboard.budget.totalBudget===null?t("dashboard.totalUnset"):amount(dashboard.budget.totalBudget,locale)}</strong></p><p>{t("dashboard.spent")}<strong className="mt-1 block">{amount(dashboard.budget.actualExpense,locale)}</strong></p><p>{t("dashboard.remaining")}<strong className="mt-1 block">{dashboard.budget.remaining===null?"-":dashboard.budget.overBudget?`${amount(Math.abs(dashboard.budget.remaining),locale)} ${t("dashboard.over")}`:amount(dashboard.budget.remaining,locale)}</strong></p></div><p className="mt-3 text-sm">{dashboard.budget.usageRate===null?"-":`${t("dashboard.usageRate")} ? ${formatPercentPoints(dashboard.budget.usageRate)}`}</p>{dashboard.budget.usageRate!==null&&<div className="mt-2 h-2 overflow-hidden rounded-full bg-zinc-100"><div className={`h-full ${dashboard.budget.overBudget?"bg-rose-600":"bg-blue-600"}`} style={{width:`${Math.min(100,Math.max(0,dashboard.budget.usageRate))}%`}}/></div>}</>}</section>
      <section className="rounded-xl border bg-white p-4 sm:p-5"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="font-semibold">{t("dashboard.topExpenses")}</h2><Link href={`${root}/reports/expense-ranking?periodType=MONTH&year=${year}&month=${month}`} className="text-sm font-medium text-blue-700 hover:underline">{t("dashboard.allRankings")}</Link></div>{dashboard.topExpenses.length===0?<p className="mt-3 text-sm text-zinc-600">{t("dashboard.noExpenses")}</p>:<ol className="mt-3 divide-y">{dashboard.topExpenses.map((item)=><li key={item.transactionUid} className="flex items-center justify-between gap-3 py-3 text-sm"><div className="min-w-0"><p title={item.memo||item.categoryName} className="truncate font-medium">{item.rank}. {item.memo||item.categoryName}</p><p className="truncate text-xs text-zinc-600">{item.categoryName} ? {formatLocalDate(item.transactionDate,"-",locale)}</p></div><strong className="shrink-0">{amount(item.amount,locale)}</strong></li>)}</ol>}</section>
      <nav aria-label={t("dashboard.quickLinks")} className="flex flex-wrap gap-2">{[[t("navigation.calendar"),`${root}/calendar?year=${year}&month=${month}`],[t("navigation.transactions"),`${root}/transactions?year=${year}&month=${month}`],[t("navigation.budget"),`${root}/budgets?year=${year}&month=${month}`]].map(([label,href])=><Link key={href} href={href} className="inline-flex min-h-11 items-center rounded-lg border bg-white px-4 text-sm">{label}</Link>)}</nav>
    </>}</main>;
}
