package com.moneybook.backend.enums;

/** 사용자에게 표시할 가계부 변경 작업 종류. */
public enum ActivityType {
    MONEY_BOOK_CREATED, OWNER_TRANSFERRED, MEMBER_INVITED, MEMBER_INVITATION_ACCEPTED, MEMBER_INVITATION_REJECTED,
    MEMBER_PERMISSION_UPDATED, MEMBER_REMOVED, CATEGORY_CREATED, CATEGORY_UPDATED, CATEGORY_DELETED,
    ACCOUNT_CREATED, ACCOUNT_UPDATED, ACCOUNT_DELETED, TRANSACTION_CREATED, TRANSACTION_UPDATED,
    TRANSACTION_DELETED, TRANSFER_CREATED, TRANSFER_UPDATED, TRANSFER_DELETED,
    RECURRING_CREATED, RECURRING_UPDATED, RECURRING_ACTIVATED, RECURRING_DEACTIVATED,
    RECURRING_DELETED, RECURRING_GENERATED, BUDGET_UPDATED, MONTH_CLOSED,
    MONTH_CLOSING_CANCELLED, SETTING_UPDATED, BACKUP_EXPORTED, BACKUP_RESTORED
}
