import { dashboardByLocale } from "./dashboardMessages";
import type { Locale } from "./config";

export const messages = {
  ko: { common: { save: "저장", cancel: "취소", delete: "삭제", edit: "수정", close: "닫기", retry: "다시 시도", loading: "불러오는 중...", language: "언어 선택", home: "홈", noData: "데이터가 없습니다.", noResults: "검색 결과가 없습니다." }, navigation: { myBooks: "내 가계부", invitations: "받은 초대", board: "게시판", account: "계정 관리", admin: "관리자", dashboard: "대시보드", calendar: "캘린더", transactions: "거래내역", transfers: "이체", recurring: "정기거래", budget: "예산", reports: "리포트", categories: "카테고리", accounts: "계좌 / 결제수단", activity: "활동내역", closing: "월 결산", settings: "가계부 설정", members: "멤버 관리", manage: "관리", book: "가계부", openMenu: "전역 메뉴 열기", mobileMenu: "모바일 전역 메뉴", menu: "메뉴" }, auth: { login: "로그인", signup: "회원가입", logout: "로그아웃", loggingOut: "로그아웃 중...", loginId: "로그인 ID", password: "비밀번호", passwordConfirm: "비밀번호 확인", nickname: "닉네임", forgot: "비밀번호를 잊으셨나요?", noAccount: "계정이 없으신가요?", hasAccount: "이미 계정이 있으신가요?", loggingIn: "로그인 중...", signingUp: "가입 중..." }, books: { title: "가계부", select: "내 가계부", create: "새 가계부 만들기", description: "참여 중인 가계부를 선택하세요.", loading: "가계부를 불러오는 중...", empty: "아직 참여 중인 가계부가 없습니다.", emptyHint: "새 가계부를 만들어 시작해 보세요.", accessChecking: "가계부 접근 권한을 확인하는 중...", accessDenied: "가계부 조회 권한이 없습니다.", accessMissing: "접근 가능한 가계부를 찾을 수 없습니다.", owner: "소유자", administrator: "관리자", backToList: "내 가계부 목록으로" }, board: { title: "게시판", write: "글쓰기" }, account: { title: "계정 관리" }, errors: { forbidden: "권한이 없습니다.", forbiddenDescription: "이 가계부에 접근할 권한이 없습니다.", backToBooks: "가계부 선택으로 돌아가기", notFound: "페이지를 찾을 수 없습니다.", notFoundDescription: "요청한 페이지가 없거나 이동되었습니다." } },
  en: { common: { save: "Save", cancel: "Cancel", delete: "Delete", edit: "Edit", close: "Close", retry: "Try again", loading: "Loading...", language: "Select language", home: "Home", noData: "No data available.", noResults: "No results found." }, navigation: { myBooks: "My books", invitations: "Invitations", board: "Community", account: "Account", admin: "Admin", dashboard: "Dashboard", calendar: "Calendar", transactions: "Transactions", transfers: "Transfers", recurring: "Recurring", budget: "Budget", reports: "Reports", categories: "Categories", accounts: "Accounts / payment methods", activity: "Activity", closing: "Monthly closing", settings: "Book settings", members: "Members", manage: "Manage", book: "Book", openMenu: "Open navigation", mobileMenu: "Mobile navigation", menu: "Menu" }, auth: { login: "Log in", signup: "Sign up", logout: "Log out", loggingOut: "Logging out...", loginId: "Login ID", password: "Password", passwordConfirm: "Confirm password", nickname: "Nickname", forgot: "Forgot your password?", noAccount: "New to MoneyBook?", hasAccount: "Already have an account?", loggingIn: "Logging in...", signingUp: "Creating account..." }, books: { title: "Books", select: "My books", create: "Create a book", description: "Choose a book you belong to.", loading: "Loading books...", empty: "You have not joined any books yet.", emptyHint: "Create a book to get started.", accessChecking: "Checking book access...", accessDenied: "You do not have permission to view this book.", accessMissing: "No accessible book was found.", owner: "Owner", administrator: "Administrator", backToList: "Back to my books" }, board: { title: "Community", write: "Write a post" }, account: { title: "Account settings" }, errors: { forbidden: "Access denied.", forbiddenDescription: "You do not have permission to access this book.", backToBooks: "Back to book selection", notFound: "Page not found.", notFoundDescription: "The requested page does not exist or has moved." } },
  ja: { common: { save: "保存", cancel: "キャンセル", delete: "削除", edit: "編集", close: "閉じる", retry: "再試行", loading: "読み込み中...", language: "言語を選択", home: "ホーム", noData: "データがありません。", noResults: "検索結果がありません。" }, navigation: { myBooks: "家計簿一覧", invitations: "招待", board: "掲示板", account: "アカウント設定", admin: "管理", dashboard: "ダッシュボード", calendar: "カレンダー", transactions: "取引", transfers: "振替", recurring: "定期取引", budget: "予算", reports: "レポート", categories: "カテゴリ", accounts: "口座・決済方法", activity: "アクティビティ", closing: "月次締め", settings: "家計簿設定", members: "メンバー管理", manage: "管理", book: "家計簿", openMenu: "ナビゲーションを開く", mobileMenu: "モバイルメニュー", menu: "メニュー" }, auth: { login: "ログイン", signup: "新規登録", logout: "ログアウト", loggingOut: "ログアウト中...", loginId: "ログインID", password: "パスワード", passwordConfirm: "パスワード（確認）", nickname: "ニックネーム", forgot: "パスワードをお忘れですか？", noAccount: "アカウントをお持ちでない方", hasAccount: "すでにアカウントをお持ちですか？", loggingIn: "ログイン中...", signingUp: "登録中..." }, books: { title: "家計簿", select: "家計簿一覧", create: "家計簿を作成", description: "参加している家計簿を選択してください。", loading: "家計簿を読み込み中...", empty: "参加中の家計簿はありません。", emptyHint: "家計簿を作成して始めましょう。", accessChecking: "家計簿へのアクセス権を確認中...", accessDenied: "この家計簿を閲覧する権限がありません。", accessMissing: "アクセス可能な家計簿が見つかりません。", owner: "オーナー", administrator: "管理者", backToList: "家計簿一覧に戻る" }, board: { title: "掲示板", write: "投稿する" }, account: { title: "アカウント設定" }, errors: { forbidden: "アクセス権限がありません", forbiddenDescription: "この家計簿にアクセスする権限がありません。", backToBooks: "家計簿選択に戻る", notFound: "ページが見つかりません。", notFoundDescription: "お探しのページは存在しないか、移動しました。" } },
  zh: { common: { save: "保存", cancel: "取消", delete: "删除", edit: "编辑", close: "关闭", retry: "重试", loading: "加载中...", language: "选择语言", home: "首页", noData: "暂无数据。", noResults: "没有搜索结果。" }, navigation: { myBooks: "我的账本", invitations: "收到的邀请", board: "社区", account: "账户设置", admin: "管理后台", dashboard: "仪表盘", calendar: "日历", transactions: "交易记录", transfers: "转账", recurring: "定期交易", budget: "预算", reports: "报表", categories: "分类", accounts: "账户 / 支付方式", activity: "活动记录", closing: "月度结账", settings: "账本设置", members: "成员管理", manage: "管理", book: "账本", openMenu: "打开导航", mobileMenu: "移动端导航", menu: "菜单" }, auth: { login: "登录", signup: "注册", logout: "退出登录", loggingOut: "正在退出...", loginId: "登录名", password: "密码", passwordConfirm: "确认密码", nickname: "昵称", forgot: "忘记密码？", noAccount: "还没有账户？", hasAccount: "已有账户？", loggingIn: "正在登录...", signingUp: "正在注册..." }, books: { title: "账本", select: "我的账本", create: "创建新账本", description: "请选择您参与的账本。", loading: "正在加载账本...", empty: "您尚未加入任何账本。", emptyHint: "创建账本即可开始使用。", accessChecking: "正在检查账本访问权限...", accessDenied: "您没有查看此账本的权限。", accessMissing: "未找到可访问的账本。", owner: "所有者", administrator: "管理员", backToList: "返回我的账本" }, board: { title: "社区", write: "发表帖子" }, account: { title: "账户设置" }, errors: { forbidden: "无权访问", forbiddenDescription: "您没有访问此账本的权限。", backToBooks: "返回账本选择", notFound: "未找到页面。", notFoundDescription: "请求的页面不存在或已移动。" } },
} as const;

const reportsByLocale = {
  ko: { summary: "요약", monthly: "월간 분석", yearly: "연간 분석", ranking: "지출 순위" },
  en: { summary: "Summary", monthly: "Monthly", yearly: "Yearly", ranking: "Expense ranking" },
  ja: { summary: "概要", monthly: "月次分析", yearly: "年次分析", ranking: "支出ランキング" },
  zh: { summary: "摘要", monthly: "月度分析", yearly: "年度分析", ranking: "支出排名" },
} as const;

const signupByLocale = {
  ko: { done: "회원가입이 완료되었습니다.", loginNext: "로그인 화면에서 새 계정으로 로그인해 주세요.", recoveryTitle: "계정 복구코드를 저장해주세요", recoveryUnavailable: "복구코드를 표시할 수 없습니다. 계정 복구 설정을 확인해 주세요.", copied: "복사했습니다", copyAll: "전체 복사", copyFailed: "복사하지 못했습니다. 코드를 직접 선택해 복사해주세요.", oneTime: "복구코드는 지금 한 번만 표시됩니다.", recoveryHelp: "보안 질문 답변을 잊었거나 다른 복구 방법을 사용할 수 없을 때 필요합니다.", storeCodes: "별도로 보관하지 않으면 기존 코드를 다시 확인할 수 없습니다.", stored: "복구코드를 저장했습니다", recoveryInfo: "계정 복구 정보", recoveryInfoHelp: "보안 질문과 답변은 비밀번호를 분실했을 때 본인 확인에 사용됩니다. 입력한 답변을 정확하게 기억해주세요.", questionLoading: "보안 질문을 불러오는 중...", questionError: "보안 질문을 불러오지 못했습니다. 잠시 후 다시 시도해 주세요.", securityQuestion: "보안 질문", chooseQuestion: "질문을 선택하세요", answer: "답변", optionalEmail: "이메일 (선택)", emailHelp: "이메일 등록은 선택사항입니다. 인증된 이메일이 있으면 비밀번호 분실 시 이메일 인증을 통해 직접 재설정할 수 있습니다. 이메일을 등록하지 않아도 서비스 이용에는 문제가 없습니다.", emailAddress: "이메일 주소", requestCode: "인증번호 받기", requesting: "요청 중...", duplicateEmail: "이미 다른 계정에서 사용 중인 이메일입니다.", verificationCode: "인증번호", verifying: "확인 중...", verify: "인증하기", codeSent: "인증번호를 전송했습니다. 10분 안에 인증을 완료해 주세요.", emailVerified: "이메일 인증이 완료되었습니다.", noEmailTip: "이메일 없이 가입하려면 이 항목을 비워두세요.", emailRequired: "가입하려면 입력한 이메일의 인증을 완료해주세요.", signup: "회원가입", existingAccount: "이미 계정이 있으신가요?", invalidSecurityAnswer: "보안 질문 답변의 앞뒤에 공백을 입력할 수 없습니다." },
  en: { done: "Your account has been created.", loginNext: "Log in with your new account.", recoveryTitle: "Save your account recovery codes", recoveryUnavailable: "Recovery codes are unavailable. Check your account recovery settings.", copied: "Copied", copyAll: "Copy all", copyFailed: "Could not copy. Select and copy the codes manually.", oneTime: "These recovery codes are shown only once.", recoveryHelp: "Use a code if you forget your security answer or cannot use another recovery method.", storeCodes: "You cannot view these codes again unless you save them separately.", stored: "I saved my recovery codes", recoveryInfo: "Account recovery", recoveryInfoHelp: "Your security question and answer help verify your identity if you forget your password. Remember your answer exactly as entered.", questionLoading: "Loading security questions...", questionError: "Could not load security questions. Please try again shortly.", securityQuestion: "Security question", chooseQuestion: "Choose a question", answer: "Answer", optionalEmail: "Email (optional)", emailHelp: "Adding an email is optional. A verified email lets you reset a forgotten password. You can use the service without adding an email.", emailAddress: "Email address", requestCode: "Send verification code", requesting: "Sending...", duplicateEmail: "This email is already in use by another account.", verificationCode: "Verification code", verifying: "Checking...", verify: "Verify", codeSent: "The code was sent. Complete verification within 10 minutes.", emailVerified: "Email verified.", noEmailTip: "Leave this blank to sign up without an email.", emailRequired: "Verify the email address before signing up.", signup: "Sign up", existingAccount: "Already have an account?", invalidSecurityAnswer: "Do not include spaces at the beginning or end of your security answer." },
  ja: { done: "アカウントを作成しました。", loginNext: "ログイン画面から新しいアカウントでログインしてください。", recoveryTitle: "アカウント復旧コードを保存してください", recoveryUnavailable: "復旧コードを表示できません。アカウント復旧設定をご確認ください。", copied: "コピーしました", copyAll: "すべてコピー", copyFailed: "コピーできませんでした。コードを選択して手動でコピーしてください。", oneTime: "復旧コードは今回のみ表示されます。", recoveryHelp: "セキュリティ回答を忘れた場合や他の復旧方法を使えない場合に必要です。", storeCodes: "別途保存しない場合、コードを再表示できません。", stored: "復旧コードを保存しました", recoveryInfo: "アカウント復旧情報", recoveryInfoHelp: "セキュリティの質問と回答は、パスワードを忘れた際の本人確認に使用します。入力した回答を正確に覚えておいてください。", questionLoading: "セキュリティの質問を読み込み中...", questionError: "質問を読み込めませんでした。しばらくしてから再試行してください。", securityQuestion: "セキュリティの質問", chooseQuestion: "質問を選択してください", answer: "回答", optionalEmail: "メールアドレス（任意）", emailHelp: "メールアドレスの登録は任意です。確認済みのメールアドレスがあれば、パスワードを忘れた際に再設定できます。登録しなくてもサービスを利用できます。", emailAddress: "メールアドレス", requestCode: "確認コードを送信", requesting: "送信中...", duplicateEmail: "このメールアドレスは別のアカウントで使用されています。", verificationCode: "確認コード", verifying: "確認中...", verify: "確認", codeSent: "確認コードを送信しました。10分以内に確認を完了してください。", emailVerified: "メールアドレスを確認しました。", noEmailTip: "メールアドレスなしで登録する場合は空欄にしてください。", emailRequired: "登録するにはメールアドレスの確認を完了してください。", signup: "新規登録", existingAccount: "すでにアカウントをお持ちですか？", invalidSecurityAnswer: "セキュリティ回答の前後に空白を入力しないでください。" },
  zh: { done: "账户已创建。", loginNext: "请前往登录页面使用新账户登录。", recoveryTitle: "请保存账户恢复码", recoveryUnavailable: "无法显示恢复码，请检查账户恢复设置。", copied: "已复制", copyAll: "全部复制", copyFailed: "复制失败，请手动选择并复制恢复码。", oneTime: "恢复码仅显示这一次。", recoveryHelp: "忘记安全问题答案或无法使用其他恢复方式时，需要使用恢复码。", storeCodes: "如果没有另行保存，将无法再次查看这些恢复码。", stored: "我已保存恢复码", recoveryInfo: "账户恢复信息", recoveryInfoHelp: "忘记密码时，安全问题和答案用于验证身份。请准确记住您输入的答案。", questionLoading: "正在加载安全问题...", questionError: "无法加载安全问题，请稍后重试。", securityQuestion: "安全问题", chooseQuestion: "请选择一个问题", answer: "答案", optionalEmail: "电子邮箱（选填）", emailHelp: "添加邮箱为可选项。验证邮箱后，忘记密码时可通过邮箱重设密码。不填写邮箱也可以使用服务。", emailAddress: "电子邮箱地址", requestCode: "发送验证码", requesting: "正在发送...", duplicateEmail: "此邮箱已被其他账户使用。", verificationCode: "验证码", verifying: "正在验证...", verify: "验证", codeSent: "验证码已发送，请在10分钟内完成验证。", emailVerified: "邮箱验证完成。", noEmailTip: "不使用邮箱注册时请留空。", emailRequired: "注册前请完成邮箱验证。", signup: "注册", existingAccount: "已有账户？", invalidSecurityAnswer: "安全问题答案的开头和结尾不能包含空格。" },
} as const;

const transactionMessages = {
  ko: { title: "거래 내역", description: "월별 수입과 지출을 확인합니다.", add: "거래 추가", searchFilter: "검색/필터", monthView: "월별 보기", searchFilters: "거래 검색 필터", startDate: "시작일", endDate: "종료일", type: "유형", all: "전체", income: "수입", expense: "지출", category: "카테고리", account: "계좌", keyword: "검색어", keywordHint: "메모, 카테고리, 계좌", minAmount: "최소 금액", maxAmount: "최대 금액", sort: "정렬", newest: "최신순", oldest: "오래된순", amountHigh: "금액 높은순", amountLow: "금액 낮은순", pageSize: "페이지 크기", apply: "검색", reset: "초기화", empty: "거래 내역이 없습니다.", noSearchResults: "조건에 맞는 거래가 없습니다.", noMonthEntries: "이 달에 등록된 거래가 없습니다.", loading: "거래를 불러오는 중...", dateRangeError: "조회 기간은 필수이며 2년 범위 이내로 지정해주세요.", amountRangeError: "금액은 0 이상이며 최소 금액은 최대 금액보다 클 수 없습니다.", previous: "이전", next: "다음", previousPage: "이전 페이지", nextPage: "다음 페이지" },
  en: { title: "Transactions", description: "Review monthly income and expenses.", add: "Add transaction", searchFilter: "Search and filters", monthView: "Monthly view", searchFilters: "Transaction filters", startDate: "Start date", endDate: "End date", type: "Type", all: "All", income: "Income", expense: "Expense", category: "Category", account: "Account", keyword: "Keyword", keywordHint: "Memo, category, or account", minAmount: "Minimum amount", maxAmount: "Maximum amount", sort: "Sort", newest: "Newest first", oldest: "Oldest first", amountHigh: "Highest amount", amountLow: "Lowest amount", pageSize: "Page size", apply: "Search", reset: "Reset", empty: "No transactions found.", noSearchResults: "No transactions match these filters.", noMonthEntries: "No transactions have been added this month.", loading: "Loading transactions...", dateRangeError: "Set a date range within two years.", amountRangeError: "Amounts must be zero or greater; minimum cannot exceed maximum.", previous: "Previous", next: "Next", previousPage: "Previous page", nextPage: "Next page" },
  ja: { title: "取引履歴", description: "月ごとの収入と支出を確認します。", add: "取引を追加", searchFilter: "検索・絞り込み", monthView: "月別表示", searchFilters: "取引の検索条件", startDate: "開始日", endDate: "終了日", type: "種類", all: "すべて", income: "収入", expense: "支出", category: "カテゴリ", account: "口座", keyword: "キーワード", keywordHint: "メモ、カテゴリ、口座", minAmount: "最低金額", maxAmount: "最高金額", sort: "並び順", newest: "新しい順", oldest: "古い順", amountHigh: "金額が高い順", amountLow: "金額が低い順", pageSize: "表示件数", apply: "検索", reset: "リセット", empty: "取引履歴はありません。", noSearchResults: "条件に一致する取引はありません。", noMonthEntries: "今月登録された取引はありません。", loading: "取引を読み込み中...", dateRangeError: "2年以内の期間を指定してください。", amountRangeError: "金額は0以上で、最低金額は最高金額以下にしてください。", previous: "前へ", next: "次へ", previousPage: "前のページ", nextPage: "次のページ" },
  zh: { title: "交易记录", description: "查看每月收入和支出。", add: "添加交易", searchFilter: "搜索和筛选", monthView: "按月查看", searchFilters: "交易筛选条件", startDate: "开始日期", endDate: "结束日期", type: "类型", all: "全部", income: "收入", expense: "支出", category: "分类", account: "账户", keyword: "关键词", keywordHint: "备注、分类或账户", minAmount: "最低金额", maxAmount: "最高金额", sort: "排序", newest: "最新优先", oldest: "最早优先", amountHigh: "金额从高到低", amountLow: "金额从低到高", pageSize: "每页条数", apply: "搜索", reset: "重置", empty: "没有交易记录。", noSearchResults: "没有符合条件的交易。", noMonthEntries: "本月尚无交易记录。", loading: "正在加载交易...", dateRangeError: "请设置两年以内的查询日期范围。", amountRangeError: "金额必须大于或等于0，最低金额不能高于最高金额。", previous: "上一页", next: "下一页", previousPage: "上一页", nextPage: "下一页" },
} as const;

const calendarMessages = {
  ko: { selectMonth: "조회 월 선택", previousMonth: "이전 달", nextMonth: "다음 달" },
  en: { selectMonth: "Choose month", previousMonth: "Previous month", nextMonth: "Next month" },
  ja: { selectMonth: "表示する月を選択", previousMonth: "前の月", nextMonth: "次の月" },
  zh: { selectMonth: "选择月份", previousMonth: "上个月", nextMonth: "下个月" },
} as const;
const signupErrorsByLocale = {
  ko: { requestFailed: "인증번호를 요청하지 못했습니다.", verifyFailed: "인증번호를 확인하지 못했습니다." },
  en: { requestFailed: "Could not request a verification code.", verifyFailed: "Could not verify the code." },
  ja: { requestFailed: "確認コードをリクエストできませんでした。", verifyFailed: "確認コードを確認できませんでした。" },
  zh: { requestFailed: "无法请求验证码。", verifyFailed: "无法验证验证码。" },
} as const;


export function translate(locale: Locale, key: string): string {
  const catalog = { ...messages[locale], reports: reportsByLocale[locale], signup: { ...signupByLocale[locale], ...signupErrorsByLocale[locale] }, transactions: transactionMessages[locale], calendar: calendarMessages[locale], dashboard: dashboardByLocale[locale] };
  const value: unknown = key.split(".").reduce<unknown>((current, part) => current && typeof current === "object" ? (current as Record<string, unknown>)[part] : undefined, catalog);
  return typeof value === "string" ? value : `⟦${key}⟧`;
}

export function getMessages(locale: Locale) {
  return { ...messages[locale], reports: reportsByLocale[locale], signup: { ...signupByLocale[locale], ...signupErrorsByLocale[locale] }, transactions: transactionMessages[locale], calendar: calendarMessages[locale], dashboard: dashboardByLocale[locale] };
}

function collectKeys(value: Record<string, unknown>, prefix = ""): string[] {
  return Object.entries(value).flatMap(([key, child]) => {
    const fullKey = prefix ? `${prefix}.${key}` : key;
    return child && typeof child === "object" && !Array.isArray(child)
      ? collectKeys(child as Record<string, unknown>, fullKey)
      : [fullKey];
  });
}

export function translationKeySets() {
  return Object.fromEntries((Object.keys(messages) as Locale[]).map((locale) => [locale, collectKeys(getMessages(locale))])) as Record<Locale, string[]>;
}
